name: SSM on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v4
      with:
        miniforge-version: latest
        activate-environment: abc2
        python-version: "3.11"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true

    - name: Install dependencies
      run: |
        conda install -y appdirs beautifulsoup4 cartopy gdal matplotlib-base numpy=1.* psutil pyproj qt-material tqdm flake8 coveralls pyyaml pytest pytest-cov
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

        conda install -y gsw netCDF4 pillow pyserial scipy
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        
        pip install PySide6
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        
        pip install --no-deps https://github.com/hydroffice/hyo2_abc2/archive/master.zip
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        
        pip install --no-deps .
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .\hyo2\ssm2 --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 .\hyo2\ssm2 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        py.test --cov
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }        
        coverage report -m
        coveralls
